manifests/client.pp, manifests/server.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client.erb, templates/server.erb
I use puppet-openvpn.
I read [this article](http://lowendtalk.com/discussion/comment/843561).
I figured it'd be useful to include.
Panda :panda_face:
=> Adds in the ability to set rcvbuf and sndbuf parameters.

README.md, manifests/ca.pp, manifests/client.pp, manifests/server.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client.erb, templates/server.erb
- Server config
- Added tls-server and tls-auth parameters to server config template
- Generate TLS key on server while setting up the CA
- Client config
- Link tls key into client config bundle
- Added x509-name parameter to client config template
- Added test for tls and x509-name support in client and server
=> Add TLS and x509-name verification support

manifests/ca.pp, manifests/client.pp, manifests/server.pp, spec/defines/openvpn_ca_spec.rb
The ensure_resource shared between server and ca seems like an anti-pattern.  I've refactored that out.
=> refactor to remove ensure_resource

README.md
- Changed `puppetlabs/puppet-concat` to `puppetlabs/puppet-stdlib` for `puppetlabs-stdlib 1.0.0+`
- Changed `puppetlabs/puppet-X` to `puppetlabs/puppetlabs-X`
=> Fixed invalid URLs in README.md in 'dependencies' region

manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
When the server is running in client mode, you have to specify
a fixed port for every vpn server. Alternativly when you set nobind
openvpn will just pick a random unused port.
=> feature (server): add nobind parameter support.

CHANGELOG.md, manifests/server.pp, spec/classes/openvpn_config_spec.rb, spec/defines/openvpn_server_spec.rb, templates/etc-default-openvpn.erb
=> Fix autostart_all behaviour (replaces #160)

manifests/init.pp, manifests/server.pp, manifests/service.pp, spec/classes/openvpn_service_spec.rb
When you have redundant pairs of firewalls you sometimes want to use
other means to start/stop the service (i.e. keepalived scripts).
This is primarly a request for comments. If somebody has a better approach, 
I'd be happy to dig into it.
=> feature: Add possibilty to not manage the openvpn service with puppet.

manifests/params.pp, spec/classes/openvpn_install_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_server_spec.rb
Currently EPEL repository contains the same version of easy-rsa package for all CentOS/RedHat versions:
http://pkgs.org/search/easy-rsa
=> fix params for old centos/redhat versions

manifests/params.pp, manifests/server.pp, manifests/service.pp, metadata.json
Some relatively minor adjustments to add compatibility for the recently released Ubuntu 15.04. 
Ubuntu now uses systemd, so have added the appropriate flag in `params.pp`. 
Unfortunately there is an issue in the latest version of puppet (3.7.2 - I think) on Ubuntu 15.04 where it thinks upstart is the default init provider - so have also amended the service resource attribute in `server.pp` accordingly.  While it isn't ideal to manually specify the service provider I don't think it's an issue as it's within a control block to limit the resource only to systemd enabled distributions. 
Please let me know if this needs adjustments, or could be improved. Happy to add tests as necessary but am relatively new to puppet testing so wasn't sure where best to stick them! 
Cheers
=> Ubuntu 15.04

.gitignore, manifests/client.pp, manifests/server.pp
Hi,
I refactor the generation of the ovpn file. Its support inline tls-auth now (see https://github.com/luxflux/puppet-openvpn/issues/175).
Concat Module is already required in metdata.json
Tested on Ubuntu 14.04 w/ puppet 3.8.2 and OpenVPN 2.3.7 for Windows (VPN client).
Also, the concat files are located in /var/lib/puppet/concat, which only read read by puppet group and root.
=> Use concat for ovpn generation.

templates/ldap.erb
BindDN/Password is required only if your LDAP server does not support anonymous binds. However, if you do not specify those options at all, they end up empty within ldap.conf anyway which leds to the following error while starting the openvpn daemon: "A parse error occured while attempting to comprehend Password, on line 4."
=> [BUGFIX] ldap.erb: use BindDN/Password only if specified

manifests/client.pp, templates/client.erb, templates/client_external_auth.erb
Prior to this, .ovpn would include the .conf file, which means the external references to files were also included.
Now the main template has been split into 2 files: client.erb (included in both .conf and .ovpn) and client_external_auth.erb (included only in .conf)
This should fix issue #187
=> Change how .conf and .ovpn files are generated

manifests/server.pp
Hi,
This change adds a missing 'file' resource required by the "exec[copy easy-rsa to openvpn config folder]"
Chers,
=> Add missing directory

manifests/server.pp
https://github.com/luxflux/puppet-openvpn/pull/191 ensures
the directory exists but when we use shared_ca, that means we will
declare multiple servers with the same ca. So ensures the directory
exists without failing for redeclaration.
=> Don't fail if shared_ca directory exist

manifests/params.pp
After upgrade to 4.0, i have error like there:
```
2016-09-25 14:37:58,973 WARN  [qtp240648626-67] [puppetserver] Puppet Unknown variable: '::openvpn::params::namespecific_rclink'. at /etc/puppetlabs/code/environments/jan/modules/openvpn/manifests/server.pp:518:38
2016-09-25 14:37:59,018 WARN  [qtp240648626-67] [puppetserver] Puppet Unknown variable: '::openvpn::params::namespecific_rclink'. at /etc/puppetlabs/code/environments/jan/modules/openvpn/manifests/server.pp:704:6
```
I simply set namespecific_rclink to false on non bsd systems
=> Fix Unknown variable: '::openvpn::params::namespecific_rclink' on non bsd systems

manifests/params.pp
openvpn-auth-pam.so has been renamed to openvpn-plugin-auth-pam.so as of Saucy
[0] and Jessie [1]. This patch makes the module use the correct path for the
module after this change.
[0] http://packages.ubuntu.com/search?mode=exactfilename&suite=saucy&section=all&arch=any&keywords=openvpn-plugin-auth-pam.so&searchon=contents
[1] https://packages.debian.org/search?mode=path&suite=jessie&section=all&arch=any&searchon=contents&keywords=openvpn-plugin-auth-pam.so
=> Correct path of openvpn-auth-pam.so on modern Debian distros.

.fixtures.yml, README.md, metadata.json
Open to suggestions on whether to do another release immediately or to merge some stuff first.
=> Breaking: Update puppet, stdlib, and concat requirements in prep for release

manifests/ca.pp, manifests/params.pp, manifests/server.pp, spec/classes/openvpn_install_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_server_spec.rb
Add a solution to the Problem described in #236 
Had in running in production for ~half a year now, with no problems...
Included some basic tests - feel free, to suggest any change or anything else
=> Add crl renewal

.sync.yml, README.md, lib/facter/openvpn.rb, manifests/deploy/client.pp, manifests/deploy/export.pp, manifests/deploy/install.pp, manifests/deploy/prepare.pp, manifests/deploy/service.pp, spec/defines/openvpn_deploy_client_spec.rb, spec/defines/openvpn_deploy_export_spec.rb, spec/spec_helper.rb, spec/unit/openvpn_module_spec.rb
proposal to integrate https://bitbucket.org/codacity/puppet-module-openvpn_client as mentioned in #231
=> add openvpn::deploy::(export/client)

manifests/client.pp, manifests/server.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client.erb, templates/server.erb
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--ns-cert-type
`ns-cert-type` is deprecated in OpenVPN and will removed in the next version of OpenVPN.
The PR adds an opt-in for the backwards compatibility to use the new option.
=> Allow to define remote-cert-tls

templates/client.erb, templates/server.erb
This change ensures that by setting cipher and tls_cipher to blank strings, they are consistently kept out of the configuration files - as opposed to invalid configuration being generated where the config keyword is generated with a blank argument.
Note that this does not change any defaults, since the Puppet module sets cipher and tls_cipher by default. Booleans can't be used, since we validate that these arguments are strings and boolean false is not a string :-)
=> Bug Fix: Ensure cipher and tls_cipher can be disabled entirely

manifests/server.pp
The documentation does not match the actual code. I decided to change the documentation since that would have the least impact on existing installations.
Closes https://github.com/voxpupuli/puppet-openvpn/issues/272
=> Changed type for port in class documentation

manifests/init.pp
Hi,
since puppet has a [automatic class paramter lookup](https://puppet.com/docs/puppet/5.5/hiera_automatic.html), `hiera_hash` or even `lookup` isn't required.
This change is *maybe* not BC.
=> Remove deprecated hiera_hash

metadata.json
To fix broken modules dependencies management . 
With current settings in `metadata.json` a fresh install get the following error message : 
```
Error: Could not install module 'puppetlabs-concat' (???)
No version of 'puppetlabs-concat' can satisfy all dependencies
Use `puppet module install --ignore-dependencies` to install only this module
```
It will permit to merge the PR #292
=> move concat version_requirement to >= 3.0.0 < 6.0.0

manifests/params.pp, manifests/server.pp, spec/classes/openvpn_config_spec.rb, spec/classes/openvpn_init_hiera_spec.rb, spec/classes/openvpn_init_spec.rb, spec/classes/openvpn_install_spec.rb, spec/classes/openvpn_service_spec.rb, spec/default_module_facts.yml, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_client_specific_config_spec.rb, spec/defines/openvpn_deploy_client_spec.rb, spec/defines/openvpn_deploy_export_spec.rb, spec/defines/openvpn_revoke_spec.rb, spec/defines/openvpn_server_spec.rb
update `params.pp` to be up to date with current `metadata.json`
Fixes #291
=> update supported OSes in params.pp

README.md
This fixes the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: Stdlib::Port::Unprivileged (file: /etc/puppetlabs/code/modules/openvpn/manifests/server.pp, line: 481, column: 11) on node
```
`Stdlib::Port::Unprivileged` functionality was only introduced at version 4.25.0
=> Update puppetlabs-stdlib dependency version in README

manifests/params.pp
the default easy-rsa package in FreeBSD gets easy-rsa 3.0.5
which for some reason does not work correctly in puppet-openvpn
under FreeBSD platform ( of course with changed $default_easyrsa_ver )
Therefore, temporarily specify the correct easy-rsa 2x package name
for FreeBSD: https://www.freshports.org/security/easy-rsa2/
I will try to look soon for easy-rsa 3.0.5 and puppet-openvpn error
with FreeBSD platform.
Tested on:
FreeBSD 11
FreeBSD 12
( Puppet client: puppet5-5.5.6, Puppet server: 5.3.5 )
=> FreeBSD: change additional_packages to easy-rsa2

manifests/ca.pp
On a Raspberry Pi B+ the Diffie-Hellman  parameter generation for
a 2048 key was measured to take 229m45.379s wall clock time.
Set the respective command's timeout 50% above this, to prevent
the corresponding rule from timing out.
Fixes #316
=> Set DH timeout to accommodate low performance CPU

manifests/server.pp, spec/acceptance/openvpn_spec.rb
when the custom fact was created to distinguish easyrsa version, it was not considered for triggering adapted command when crl is renewed.
Fixes #318
=> consider the easyrsa version to trigger the renew crl command

manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
Since 8.0.0 it's not possible to choose `tcp4` or `tcp6` as `proto` for an openvpn server.
N/A
=> Allow 4 and 6 suffix inside proto to limit ip4 or ip6 connection only.

manifests/deploy/export.pp
When fiddling around with server names in the configuration, you'd have
to do a clean sweep of the whole configuration to ensure that there are
no problems with the fact existence and the ordering.
Using dig (and has_key for compatibility reasons to not change anything
front-facing), we can avoid this problem.
=> Use stdlib functions for hash key discovery

manifests/client.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb
Allow newer compress option at client config since comp-lzo is deprecated
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#a--comp-lzo
=> Adjust clients $compression type to match servers

manifests/client_specific_config.pp
Signed-off-by: Florian Pritz <florian.pritz@rise-world.com>
=> Add option to disable ordering dependencies on Openvpn::Client

manifests/server.pp, spec/defines/openvpn_server_spec.rb
If the logfile path is set to a subdir (e.g.
/var/log/openvpn/$name/openvpn.log) someone needs to create that path.
This is a good a place as any to add that feature.
Signed-off-by: Florian Pritz <florian.pritz@rise-world.com>
=> Optionally manage logfile parent directory

templates/server.erb
Update server.erb - fix proto for tcp client mode so that it sets:
proto tcp
rather than
proto tcp-server
=> Update server.erb - fix proto for tcp client mode

REFERENCE.md, manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
This change allows packaging scripts with the `server` instance.
Example usage:
```
openvpn::server { 'test-site':
....
up => '/etc/openvpn/test-site/scripts/add-tap-to-bridge.sh',
scripts => {
"add-tap-to-bridge.sh" => {content => 'a'},
},
}
```
Anything that can go in a regular Puppet `file` resource can be used in the hash including `template`, `source`, and `content`.
`up`, `down`, `client-connect` and `client-disconnect` scripts will be checked for `/` and be considered to be in the `scripts` folder otherwise.
Tests pass locally.
=> Add scripts with server

README.md
Link points to fork which is not up to date.
=> Fix contributor list link

README.md
This commit simply updates the link to the REFERENCE.md file, so
that it points at the one on github, rather than being a broken
link.
n/a
=> Repair link to REFERENCE.md in README.md

manifests/revoke.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_revoke_spec.rb
This change makes it possible to revoke certificates when easyrsa version 3.x is used. There currently is an open PR open for this issue, however this has not had an update since March 2019, therefore I am opening this PR. See: #338 
The `remote_host` parameter is set, because the expected value of
`foo.example.com` is not evaluated correctly on ArchLinux.
Fixes #331
=> Enable revocation when easyrsa version 3.0 is used

.sync.yml, .travis.yml, REFERENCE.md, data/defaults.yaml, data/family/FreeBSD.yaml, data/family/RedHat/8.yaml, manifests/ca.pp, manifests/client.pp, manifests/client_specific_config.pp, manifests/init.pp, manifests/revoke.pp, manifests/server.pp, metadata.json, spec/acceptance/openvpn_spec.rb, spec/classes/openvpn_init_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_client_specific_config_spec.rb, spec/defines/openvpn_server_spec.rb, spec/spec_helper_acceptance.rb, templates/etc-rc.d-openvpn.erb, templates/server.erb, templates/vars-30.epp, templates/vars.erb
Redhat 8 has made a number of changes to openvpn.
=> Add RHEL 8 support

manifests/revoke.pp, spec/acceptance/openvpn_spec.rb, spec/defines/openvpn_revoke_spec.rb
An issue was raised informing that the revocation command is incorrect.
This was diagnosed to indeed be the case. As the `$name` variable in
context of `revoke.pp` does not evalute to `server name` but instead
`client name`. The exec for the crl renew was updated to clarify which server
it's done for and to prevent duplicate `exec` resource names.
Fixes #374
=> Fixes #374 - Revocation command update and crl renew

spec/defines/openvpn_server_spec.rb, templates/server.erb
Currently the openvpn option called status is mandatory and set with /var/log/openvpn/${name}-status.log as default.
However this parameter is not mandatory in the openvpn config. If this parameter is omitted, every log will be append to openvpn.log.
=> Update code to set status parameter optional

.github/workflows/ci.yml, data/family/RedHat/6.yaml, metadata.json
CentOS 6 is EOL and the tests don't pass anymore. We need to drop
support for it.
=> Drop CentOS 6 support

manifests/client.pp
EasyRSA version 3 and above has renamed some environment vars and then source by default the "vars" file. So client.pp allow override the "expire" for certificates but do not handle this change.
You can notice here that the "vars" template handle correctly the change https://github.com/voxpupuli/puppet-openvpn/blob/master/templates/vars-30.epp#L59 but not client.pp
=> fix(client): Handle expire value for easyrsa version 3

.github/workflows/ci.yml, data/family/Debian/11.yaml, lib/facter/easyrsa.rb, metadata.json, spec/acceptance/openvpn_spec.rb, spec/classes/openvpn_init_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb
=> Add Debian 11 support

.github/workflows/ci.yml, README.md, REFERENCE.md, lib/facter/easyrsa.rb, manifests/client.pp, manifests/server.pp, metadata.json, spec/classes/openvpn_init_spec.rb, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client.erb, templates/server.erb
Since https://github.com/voxpupuli/puppet-openvpn/pull/410 would introduce a breaking change, I would recommend to include this breaking change, too.
OpenVPN is going to remove the compression feature. I would disable compression by default. That results that new OpenVPN servers are future proof by default.
OpenVPN not longer recommends to define a cipher, since OpenVPN use (and enforce in upcoming version) cipher negotiation. For 2.4 compability, the 'AES-256-CBC' isn't a good default anymore. Using 'AES-256-GCM' as default is much better here, since it's the default cipher of the cipher negotiation.
> Sep 16 22:52:56 PI openvpn[961]: DEPRECATED OPTION: --cipher set to 'AES-256-CBC' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM). Future OpenVPN version will ignore --cipher for …
=> Disable compression and set cipher to AES-256-GCM by default

.github/workflows/ci.yml, lib/facter/easyrsa.rb, metadata.json, spec/classes/openvpn_init_spec.rb
From: https://github.com/voxpupuli/puppet-openvpn/pull/412#issuecomment-922243167
> We can drop it along with Debian 9.
I wouldn't. https://wiki.debian.org/LTS. It is still supported until 2022.
~~I'm going to modify the actions, since the logic will be changed in modulesync 4.2. See: https://github.com/voxpupuli/puppet-openvpn/pull/411~~ Looks like it's not ready. (tests failing)
=> Drop Ubuntu 16.04

REFERENCE.md, manifests/client.pp, manifests/server.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client.erb, templates/server.erb
https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--ns-cert-type
The OpenVPN parameter `--ns-cert-type` is deprecated since some OpenVPN version. `--remote-cert-tls` is a drop-in replacement. Current OpenVPN versions map `--ns-cert-type` to `--remote-cert-tls` and raise a deprecation warning.
We could drop `--ns-cert-type` (default to true in this module) and set `--remote-cert-tls` (default to false in this module) to true.
This is a breaking change, since client configs needs to be re-generated.
**Note for affected users**
You can still define `ns-cert-type` through `custom_options`.
=> Replace ns_cert_type with remote_cert_tls (**client config regeneration needed**)

README.md, Vagrantfile, vagrant/provision_module.sh, vagrant/server.pp
This PR unbreak the Vagrant environment which no longer worked because Ubuntu 16.04 was too old and installation of librarian-puppet failed. Instead of trying to fix an EOL operating system migrate to Ubuntu 20.04 instead and fix all the things that need fixing.
Vagrant now makes use of Puppet 7 from Puppetlabs. This avoids some warnings triggered by the default, EOL version of Puppet (5.5) in Ubuntu 20.04.
Some of the issues that were identified were generic and not related to the operating system upgrade.
=> Unbreak vagrant

REFERENCE.md, manifests/client_specific_config.pp, spec/defines/openvpn_client_specific_config_spec.rb, templates/client_specific_config.erb
Currently, the openvpn::client and openvpn::server classes both support
custom_options.  Modify openvpn::client_specific_config to also support
custom_options.
(no issues)
=> Support custom_options in client_specific_config

REFERENCE.md, manifests/ca.pp, manifests/revoke.pp, manifests/server.pp, spec/acceptance/openvpn_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_server_spec.rb, templates/vars-30.epp
In most of the time, the `Country/Province/City/Org/OU/email` are pointless for OpenVPN servers. easy-rsa introduce cn_only ad DN mode to omit `Country/Province/City/Org/OU/email` values.
```
#
#set_var EASYRSA_DN	"cn_only"
```
This PR also remove the manual generation of the in favor of `easyrsa gen-crl` command, since the old variant was not compatible cn_only mode. `gen-crl` put the crl.pem in private folder of the easyrsa PKI folder, a manual copy is needed.
This PR is in draft mode for get some early reviews. Since this PR is in conflict with #431, I propose the focus should be on #431. After merge of #431, I'll do a rebase here.
=> Add support for easyrsa X509 DN mode 'cn_only'

manifests/server.pp, spec/defines/openvpn_server_spec.rb
Small patch to fix the path of crl.pem introduced by https://github.com/voxpupuli/puppet-openvpn/pull/432 by @jkroepke
The cp fail with : 
```
'./easyrsa gen-crl && cp ./keys/crl.pem /etc/openvpn/10.9.200.0 255.255.255.0/crl.pem' returned 1 instead of one of [0]
change from 'notrun' to ['0'] failed: './easyrsa gen-crl && cp ./keys/crl.pem /etc/openvpn/10.9.200.0 255.255.255.0/crl.pem' returned 1 instead of one of [0] (corrective)
```
Certainly a cut and paste problem. In manifests/revoke.pp, $server is the correct variable but not in server.pp
=> Fix path for crl_auto_renew with easy_rsa 3.0

REFERENCE.md, manifests/server.pp, templates/server.erb
Make ecdh-curve optional, if no dh key is defined.
In OpenVPN 2.5 (I initially test the EC keys with OpenVPN 2.4), define ecdh-curve will throw an warning
> Consider setting groups/curves preference with tls-groups instead of forcing a specific curve with ecdh-curve.
=> Make ecdh-curve optional
