manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
Conflicts:
spec/defines/openvpn_server_spec.rb
templates/server.erb
=> feat (server): add fragment parameter support

manifests/params.pp, manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
=> pam plugin path customization

Gemfile, README.md, manifests/init.pp, spec/classes/openvpn_init_hiera_spec.rb, spec/fixtures/hiera/hiera.yaml, spec/fixtures/hiera/test.yaml, spec/spec_helper.rb
Tested on Ubuntu 12.04 / 14.04
=> feature: Add means to define openvpn server, clients etc. using hiera.

manifests/ca.pp, manifests/client.pp, manifests/client_specific_config.pp, manifests/config.pp, manifests/init.pp, manifests/install.pp, manifests/params.pp, manifests/revoke.pp, manifests/server.pp, manifests/service.pp, spec/defines/openvpn_server_spec.rb, templates/etc-rc.d-openvpn.erb, templates/server.erb, templates/vars.erb
=> Freebsd compatability rebased again

CHANGELOG.md, manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
=> Add Portshare config option

templates/server.erb
Hi,
I have fixed small typo with parameter call on line 136, there wasn't @
=> Fixed typo in paramater call

manifests/client.pp
Fixes #200 if working with exported_ressources like i am
=> Fixes #200

metadata.json
Replaces #205, Fixes #202, Fixes #205
=> Relax puppetlabs-concat dependency

manifests/server.pp
=> fix broken namespecific rclink

manifests/client.pp, manifests/params.pp
ref https://github.com/luxflux/puppet-openvpn/issues/172
=> Add rhel6 support for ldap auth plugin

.msync.yml, .rubocop.yml, .travis.yml, Gemfile
=> modulesync 1.2.1

CHANGELOG.md, metadata.json
Since 4.1.0 failed, this will be a final release before we update metadata.
=> Release 4.1.1

metadata.json
=> Upped version requirement of concat and added Debian 9 (stretch)

.msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, spec/acceptance/nodesets/docker/debian-7.yml, spec/acceptance/nodesets/docker/debian-9.yml
=> modulesync 1.4.1

manifests/init.pp
=> replace validate_* with datatypes in init.pp

CHANGELOG.md, metadata.json
=> release 7.1.0

.msync.yml, .travis.yml, Gemfile, spec/acceptance/nodesets/fedora-26-x64.yml, spec/acceptance/nodesets/fedora-27-x64.yml, spec/spec_helper.rb
=> modulesync 1.8.0

CHANGELOG.md, metadata.json
=> release 7.2.0

manifests/init.pp
=> Remove deprecated hiera_hash

.travis.yml, lib/facter/easyrsa.rb, manifests/ca.pp, manifests/client.pp, manifests/params.pp, manifests/server.pp, spec/acceptance/01_openvpn_server_spec.rb, spec/acceptance/02_openvpn_client.rb, spec/acceptance/openvpn_server_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/spec_helper_acceptance.rb, templates/server.erb, templates/vars-30.epp
A rework of PR #278 
Fixes #269
=> use new fact easyrsa to configure easyrsa 2 or 3

.msync.yml, .sync.yml, .travis.yml
=> modulesync 2.0.0

CHANGELOG.md, metadata.json
=> prepare release 7.4.0

.fixtures.yml, .github/CONTRIBUTING.md, .msync.yml, .travis.yml, Gemfile, metadata.json, spec/classes/coverage_spec.rb, spec/default_facts.yml, spec/spec_helper.rb, spec/unit/openvpn_module_spec.rb
=> modulesync 2.2.0 and allow puppet 6.x

.github/PULL_REQUEST_TEMPLATE.md, .msync.yml, .travis.yml, .travis/setup.sh, Gemfile, README.md, Rakefile, metadata.json, spec/acceptance/openvpn_spec.rb
=> modulesync 2.5.1 and drop Puppet 4 support

CHANGELOG.md, metadata.json
=> Release v8.1.0

spec/defines/openvpn_client_specific_config_spec.rb, templates/client_specific_config.erb
Added double quotes to push options which did not have double quote
Fixes issue #329
=> use double quotes on all push options

.github/CONTRIBUTING.md, .msync.yml, .sync.yml, .travis.yml, Dockerfile, Gemfile, Rakefile
=> modulesync 2.7.0

manifests/ca.pp, manifests/client.pp, manifests/server.pp, spec/defines/openvpn_client_spec.rb, spec/defines/openvpn_server_spec.rb, templates/client_external_auth.erb, templates/server.erb
Add `--tls-crypt` in alternative to tls auth (new feature since 2.4)
=> Add tls_crypt

manifests/client_specific_config.pp, spec/defines/openvpn_client_specific_config_spec.rb, templates/client_specific_config.erb
So IPv6 can be configured as well.
=> client_specific_config: add support for ifconfig-ipv6-push

templates/vars-30.epp
Small fix for overlooked variable KEY_DIR in vars-30 template
Fixes #336
=> Updated KEY_DIR to match new variable

manifests/client_specific_config.pp, templates/client_specific_config.erb
=> cleanup types in openvpn::client_specific_config

.github/CONTRIBUTING.md, .msync.yml, .travis.yml, Gemfile, spec/spec_helper.rb
=> modulesync 2.8.0

REFERENCE.md, manifests/server.pp, spec/defines/openvpn_server_spec.rb, templates/server.erb
Title basically says it all. Tests pass and documentation added.
=> Add remote-random and remote-random-hostname to managed server parameters

lib/facter/easyrsa.rb
This PR add easyrsa fact for Debian 10. 
No issue has been created for this issue.
=> Add debian buster to collect easyrsa fact

.github/CONTRIBUTING.md, .rubocop.yml, .sync.yml, Gemfile
=> modulesync 2.10.1

Gemfile
=> modulesync 2.12.0

.sync.yml, .travis.yml, data/family/Debian/10.yaml, metadata.json, spec/acceptance/openvpn_spec.rb, spec/classes/openvpn_init_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb, spec/spec_helper_acceptance.rb
Add Debian 10 (buster) support
Fixes #372 (superseeds)
=> Add buster support

.github/SECURITY.md, .msync.yml, .rubocop.yml, .travis.yml, Gemfile, manifests/ca.pp, manifests/client.pp, manifests/client_specific_config.pp, manifests/config.pp, manifests/deploy/client.pp, manifests/deploy/export.pp, manifests/deploy/install.pp, manifests/deploy/prepare.pp, manifests/deploy/service.pp, manifests/init.pp, manifests/install.pp, manifests/revoke.pp, manifests/server.pp, vagrant/client.pp
=> modulesync 3.0.0 & puppet-lint updates

CHANGELOG.md, metadata.json
=> release 8.3.0

.sync.yml, .travis.yml, README.md, metadata.json, spec/classes/openvpn_init_spec.rb
=> Drop EOL Debian 8 support

.github/workflows/ci.yml, data/family/Debian/20.04.yaml, lib/facter/easyrsa.rb, metadata.json, spec/acceptance/openvpn_spec.rb, spec/classes/openvpn_init_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb
=> Add Ubuntu 20.04 support

spec/defines/openvpn_ca_spec.rb
puppetlabs/stdlib introduced [this](https://github.com/puppetlabs/puppetlabs-stdlib/commit/77a9c07c9e64f03b12a4d8068941609f44829c8b) change
=> Change ensure to "installed" instead of "present" in specs

metadata.json
=> Allow puppetlabs/concat and puppetlabs/stdlib 7.x

README.md, data/family/Solaris.yaml, lib/facter/easyrsa.rb, metadata.json
Tested on a SmartOS base64 zone.
(no issues)
=> Add basic support for Solaris/Illumos/SmartOS

.github/workflows/ci.yml, data/family/Debian/22.04.yaml, lib/facter/easyrsa.rb, metadata.json, spec/acceptance/openvpn_spec.rb, spec/defines/openvpn_ca_spec.rb, spec/defines/openvpn_client_spec.rb
=> Add Ubuntu 22.04

.github/CONTRIBUTING.md, .msync.yml, Gemfile, spec/spec_helper.rb
=> modulesync 5.3.0

CHANGELOG.md, metadata.json
=> Release 10.3.0

.github/workflows/ci.yml, REFERENCE.md, metadata.json
=> Drop CentOS and Redhat 7 support

REFERENCE.md, metadata.json
This PR also serves to identify failing tests
=> Drop Ubuntu 18.04 support

REFERENCE.md, metadata.json
=> Drop Debian 9 and 10 support

lib/facter/easyrsa.rb, metadata.json
=> Drop Ubuntu 20.04 support

lib/facter/easyrsa.rb
=> clean esyrsa fact code

lib/facter/easyrsa.rb
=> Fix easyrsa fact
